### ISSUE TITLE
Aiuda

### ISSUE THREAD

**Issue by akaminetzkyp** [KnowYourselves/BaconPancakes#40]
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ZeroDivisionError: division by zero
```

**Comment by KnowYourpotato** [comment]
En una escala de no a si tu pregunta **SI** es googlable.
https://stackoverflow.com/questions/29836964/error-python-zerodivisionerror-division-by-zero

Salu2

**Comment by akaminetzkyp** [comment]
Gracias!
